### ISSUE TITLE
Skip reads pre-processing with fasta files as input

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#103]
Se debe crear una opción en wombat_config.py donde se pueda omitir SPAdes y todo lo anterior. Se puede llamar por ejemplo: 
`assembled_genomes: False # Skip read quality control and assembly if set to True (you need assembled genomes in fasta files as input). If not, set it to False. Default: False`

Cuando se active esta opción, el workflow empezará en el siguiente paso a SPAdes, es decir, con el ordenamiento en caso de que se indique genoma de referencia.

Supongo que será necesario indicar en un archivo el nombre de las Samples y sustituir Forward/Reverse por la ruta de localización del fasta de cada Sample.

**Comment by JoseBarbero** [comment]
Ya está añadido. He hecho varias pruebas y parece que no da problemas, pero no cierro el issue de momento porque es un cambio que afecta a muchas funcionalidades y es posible que encontremos algún fallo todavía.

**Comment by JoseBarbero** [comment]
Ya está añadido. Antes de ejecutarlo con todas las cepas intenta probar con alguna ejecución más pequeña porque es un cambio que afecta a muchas funcionalidades y puede que encontremos algún fallo. Yo he hecho varias pruebas y de momento me funciona bien.

**Comment by ireneortega** [comment]
De acuerdo, tengo una duda. ¿Qué forma concreta debe tener el archivo **input_files.csv**? ¿La columna de la ruta de localización de los archivos fasta debe tener un nombre específico?

**Comment by JoseBarbero** [comment]
He intentado mantener el formato de fichero input_files.csv para no complicarlo mucho. Habría que poner la ruta al fichero fasta tanto en la columna Forward como en la columna Reverse. Solo se tiene en cuenta la columna Forward pero así nos aseguramos de que no haya problemas de formato por dejar la columna vacía.

**Comment by ireneortega** [comment]
Fenomenal, todo correcto. Una única cosa, en el wombat_report.csv, deben aparecer también las siguientes columnas (solo sale ContigLen): 

Contigs | GenomeLen | ContigLen | N50 | GC | DepthCov (X)
-- | -- | -- | -- | -- | --

Ahora mismo, tiene esta forma:


Sample | ContigLen | ST | clonal_complex | CDS | CRISPRs | rRNAs | tRNAs | BETA-LACTAM | TETRACYCLINE | Total (77) | adhesion(10) | capsule(2) | chemotaxis(5) | colonization(1) | invasion(6) | iron(4) | los(5) | motility(11) | n-linked_glycosylation(1) | stress(16) | t6ss(13) | toxin(3)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ireneortega** [comment]
Ha salido este error:
```
Traceback (most recent call last):
  File "wombat.py", line 12, in <module>
    from terminal_banner import Banner
ModuleNotFoundError: No module named 'terminal_banner'
```

**Comment by JoseBarbero** [comment]
¿Eso ha sido con el entorno de conda activado?
De todas formas he encontrado un pequeño bug que quiero solucionar. En un rato cuando lo tenga te aviso.

**Comment by ireneortega** [comment]
Sí, tienes razón, sentía que algo se me olvidaba. 
De acuerdo.

**Comment by JoseBarbero** [comment]
Ya está solucionado. Puedes ejecutarlo cuando quieras.
Si quieres hacer una prueba pequeña antes por asegurarte, lo veo bien por si acaso, no vaya a fallar algo en ese equipo.

**Comment by ireneortega** [comment]
[wombat.log](https://github.com/JoseBarbero/Wombat/files/4938004/wombat.log) ¿El error indicado es problema de nuestra conexión? Durante la ejecución, he estado utilizando Internet sin problemas.

**Comment by JoseBarbero** [comment]
Parece un fallo de conexión, sí. Estoy intentando acceder al equipo desde remoto y no puedo conectarme, parece que ahora tampoco tiene red.

**Comment by ireneortega** [comment]
El lunes cuando lo encienda te aviso, no te preocupes hasta entonces.

**Comment by ireneortega** [comment]
Está encendido

**Comment by JoseBarbero** [comment]
Prueba a lanzar la misma ejecución que lanzaste el otro día. Si era un error de conexión no creo que vuelva a pasar.

**Comment by ireneortega** [comment]
Con la ejecución de 2 cepas ha salido bien. Después, con las restantes, ha salido este error:

```
/home/instalador/anaconda3/envs/wombat/lib/python3.6/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)
Traceback (most recent call last):
  File "wombat.py", line 1557, in <module>
    mlst_postprocessing(mlst_dir+"/"+mlst_out_file, mlst_dir+"/MLST_edited.txt")
  File "wombat.py", line 311, in mlst_postprocessing
    new_row.append(database.loc[database["ST"] == row[2]]["clonal_complex"].values[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by JoseBarbero** [comment]
Acabo de subir un cambio que debería solucionarlo. Cuando puedas actualiza y prueba de nuevo.

**Comment by ireneortega** [comment]
Ahora se ha ejecutado hasta el final, pero la columna de clonal_complex en MLST_edited.txt no se rellena correctamente (aparece `-` en todas las filas). No sé si tiene que ver con este mensaje que ha sallido al final:

```
/home/instalador/anaconda3/envs/wombat/lib/python3.6/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)
```

**Comment by JoseBarbero** [comment]
Vale, el problema era que estaba comparando tipos diferentes cuando buscaba en la base de datos que sacamos de http://rest.pubmlst.org/db/pubmlst_campylobacter_seqdef/schemes/1/profiles_csv

El caso es que antes, con las pruebas que hacía yo, el tipo no cambiaba porque todos los valores de la segunda columna del fichero MLST.txt tenían un número, pero en tus cepas había columnas que tenían "-", así que leía toda la columna como cadenas de texto en vez de como enteros, aunque el resto de valores sí lo fuesen. Terminaba comparando cadenas con enteros y fallaba.
Lo dejo escrito porque era un fallo complejo de encontrar, por si me vuelve a pasar en un futuro.

Ya está el cambio subido.

**Comment by ireneortega** [comment]
Ahora el error es en la generación de los roary_plots:

```
Traceback (most recent call last):
  File "utils/roary_plots.py", line 131, in <module>
    line = line.replace(sample+":", sample+"{"+mlst_data.loc[mlst_data["Sample"] == sample]["clonal_complex"].values[0]+"}:").replace(" ", "_")
TypeError: must be str, not float
```

Solo se genera el pangenome_frequency.png.

**Comment by JoseBarbero** [comment]
No tengo acceso a vuestro equipo (supongo que está apagado) así que no puedo probarlo, pero he subido un cambio que debería haberlo arreglado. 
Perdona por tantos bugs, me estoy encontrando cosas nuevas que con las otras cepas no encontraba.
