### ISSUE TITLE
New tool PhasomeIt

### ISSUE THREAD

**Issue by ireneortega** [JoseBarbero/Wombat#110]
También queremos incorporar una nueva herramienta Phasomeit https://github.com/JackAidley/PhasomeIt. Te adjunto dos versiones:
–	Phasomelt-master es la versión 1.1.1. Me generó este error https://github.com/JackAidley/PhasomeIt/issues/2#issue-652456121. El problema era que había que indicar la carpeta con los archivos FASTA como inputs y cuando lo hacía me salía un error diciendo que no había indicado una carpeta y cuando lo hacía como explica, que era un directorio como ves en el error: 

```
irene@irene-VirtualBox:~/PhasomeIt_v1_1_1/PhasomeIt$ python3 phasomeit.py -t ./NCTC11168 -c 0 --firstSpecies jejuni --firstStrains NCTC11168
Traceback (most recent call last):
  File "phasomeit.py", line 171, in <module>
    main()
  File "phasomeit.py", line 154, in main
    plugins = [SpeciesAnnotator(args.target, settings.metadataCsv)]
  File "/home/irene/PhasomeIt_v1_1_1/PhasomeIt/speciesannotator.py", line 10, in __init__
    with open(csvFilename, newline='') as csvFile:
IsADirectoryError: [Errno 21] Is a directory: './NCTC11168'
```

–	PashomeIt_v1_1_2. El autor reconoció el error anterior, pero no había actualizado el repositorio en GitHub hasta entonces. Después, lo hizo y se descarga el archivo comprimido adjunto.  Me generó este error: `ValueError: Your XML file was empty` Por lo que estuve mirando parece que tiene que ver con BLAST, aunque el desarrollador me dijo que podría ser problema de los archivos de entrada. Me salía siempre ese error, excepto una vez que siguió el proceso y me salió una pregunta de si quería ejecutar además otra cosa (no recuerdo muy bien cuál era), por si te sale a ti. No sé si puede ser un problema de las dependencias que utiliza o si cambiando la versión de BLAST que necesita, se arreglaría. Te adjunto el log file de esta versión [Phasomeit_v1.1.2_execution_process.txt](https://github.com/JoseBarbero/Wombat/files/4911155/Phasomeit_v1.1.2_execution_process.txt)

**Comment by JoseBarbero** [comment]
Estoy probando esto y me ha dado un error diferente con cada versión de Python que he probado. ¿En qué versión estás tú?

**Comment by ireneortega** [comment]
En mi máquina virtual tengo Python 3.6.9, natsort 6.2.1 y BLAST 2.9.0+, aunque he probado también con Python 3.6.9, Biopython version 1.77, natsort 4.0.3 y BLAST 2.6.0+. En ambos casos me sale ahora este nuevo error que no sé si te coincidirá a ti 
[_phasomeit.log](https://github.com/JoseBarbero/Wombat/files/4918706/_phasomeit.log). El error del otro día era utilizando Python 3.6.9, natsort 6.2.1 y BLAST 2.9.0+.
